name: benchmark 

on:
  push:
    branches: [ main ]

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Rust 1.66.1 
      uses: actions-rs/toolchain@v1
      with:
          toolchain: 1.66.1 
          override: true
          components: rustfmt, clippy
    - uses: actions/checkout@v3
    - name: Python3 Build
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install test dependencies
      run: pip install -r requirements.txt
    - name: Run benchmark
      run: make benchmark-action
    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        tool: 'cargo'
        output-file-path: output.txt
        benchmark-data-dir-path: "."
        # Access token to deploy GitHub Pages branch
        github-token: ${{ secrets.GITHUB_TOKEN }}
        # Push and deploy GitHub pages branch automatically
        auto-push: true
        alert-threshold: '130%'
        comment-on-alert: true
        alert-comment-cc-users: '@unbalancedparentheses'
    - name: Clean benches
      run: make clean
