name: benchmark_pr 

on:
  pull_request:
    branches: [ '*' ]

jobs:
  fetch-iai-results:
    runs-on: ubuntu-22.04
    steps:
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: 1.66.1
          override: true
          profile: minimal
    - name: Python3 Build
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.base.sha }}
    - name: Install test dependencies
      run: |
        pip install -r requirements.txt
        sudo apt update
        sudo apt install -y valgrind
    - name: Initialize IAI cache for ${{ github.event.pull_request.base.sha }}
      uses: actions/cache@v3
      id: cache-iai-results
      with:
        path: |
          target/iai/
          !target/iai/**.old
        key: ${{ runner.os }}-iai-benchmark-cache-${{ github.event.pull_request.base.sha }}
        restore-keys: |
          ${{ runner.os }}-iai-benchmark-cache-
    - name: Run iai benchmarks
      if: ${{ steps.cache-iai-results.outputs.cache-hit != 'true' }}
      run: make iai-benchmark-action
  run-iai-benchmark:
    needs: fetch-iai-results
    runs-on: ubuntu-22.04
    steps:
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: 1.66.1
          override: true
          profile: minimal
    - name: Python3 Build
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install test dependencies
      run: |
        pip install -r requirements.txt
        sudo apt update
        sudo apt install -y valgrind
    - name: Initialize IAI cache for ${{ github.event.pull_request.base.sha }}
      uses: actions/cache@v3
      id: cache-iai-results
      with:
        path: |
          target/iai/
          !target/iai/**.old
        key: ${{ runner.os }}-iai-benchmark-cache-${{ github.event.pull_request.base.sha }}
        restore-keys: |
          ${{ runner.os }}-iai-benchmark-cache-
    - name: Run iai benchmarks
      run: make iai-benchmark-action
